import { appModules, sourceModules } from "./registry.js";

/**
 * Sources that do not work on the hosted Azure endpoint, and why. Kept here so every published
 * "N of M sources work hosted" number comes from one place (see docs/counts.json and src/counts.test.ts).
 */
export const HOSTED_LIMITS: Record<string, string> = {
  nta: "NTA realtime needs an operator key that the hosted service does not have."
};

/** ireland_catalogue, ireland_describe, ireland_call, ireland_about. */
export const META_TOOLS = 4;
export const PROMPTS = ["area_profile", "commute_check", "compare_counties"] as const;

export interface Counts {
  sources: number;
  hosted_working: number;
  hosted_limited: string[];
  operations: number;
  source_operations: number;
  cross_operations: number;
  default_tools: number;
  all_tools: number;
  prompts: number;
}

export function computeCounts(): Counts {
  const { modules, extraTools } = appModules();
  const ops = modules.flatMap((m) => m.tools);
  const sourceOps = sourceModules.reduce((sum, m) => sum + m.tools.length, 0);
  return {
    sources: sourceModules.length,
    hosted_working: sourceModules.length - Object.keys(HOSTED_LIMITS).length,
    hosted_limited: Object.keys(HOSTED_LIMITS),
    operations: ops.length,
    source_operations: sourceOps,
    cross_operations: ops.length - sourceOps,
    default_tools: META_TOOLS + extraTools.length + ops.filter((t) => t.pinned).length,
    all_tools: META_TOOLS + extraTools.length + ops.length,
    prompts: PROMPTS.length
  };
}

export const COUNTS_START = "<!-- counts:start (generated by `npm run counts`; CI checks it) -->";
export const COUNTS_END = "<!-- counts:end -->";

/** The README's definitions table. */
export function renderCounts(c: Counts): string {
  const limited = Object.values(HOSTED_LIMITS).join(" ");
  return [
    COUNTS_START,
    "| Count | Value | Definition |",
    "| --- | ---: | --- |",
    `| Data sources | ${c.sources} | Upstream public-data sources, one module each. The \`cross\` combiner is not a source. |`,
    `| Working on the hosted endpoint | ${c.hosted_working} of ${c.sources} | ${limited} |`,
    `| Catalogue operations | ${c.operations} | ${c.source_operations} source operations plus ${c.cross_operations} cross-source ones (\`list_sources\`, \`nearby\`, \`ireland_snapshot\`), all callable through \`ireland_call\`. |`,
    `| Default tools | ${c.default_tools} | What \`tools/list\` returns: ${META_TOOLS} meta tools plus \`search\`, \`fetch\` and \`nearby\`. |`,
    `| Tools with \`?toolsets=all\` | ${c.all_tools} | Every operation as a typed tool, plus the ${META_TOOLS} meta tools, \`search\` and \`fetch\`. |`,
    `| Prompts | ${c.prompts} | ${PROMPTS.map((p) => `\`${p}\``).join(", ")}. |`,
    COUNTS_END
  ].join("\n");
}

/** The README's one-line live-ops summary, taken from docs/live-all-ops.md. */
export function liveOpsSummary(report: string): string {
  const generated = report.match(/^Generated: (\d{4}-\d{2}-\d{2})/m)?.[1];
  // DEGRADED was added later; older reports omit it.
  const line = report.match(/^Operations: (\d+) PASS, (\d+) NOT_CONFIGURED, (\d+) HOSTED_BLOCKED, (?:(\d+) DEGRADED, )?(\d+) FAIL\./m);
  if (!generated || !line) throw new Error("docs/live-all-ops.md has no Generated/Operations summary line.");
  const [pass, notConfigured, blocked, degraded, fail] = line.slice(1).map((n) => Number(n ?? 0)) as [number, number, number, number, number];
  const total = pass + notConfigured + blocked + degraded + fail;
  const notes = [
    `${notConfigured} need the NTA key`,
    ...(blocked ? [`${blocked} blocked from Azure IPs`] : []),
    ...(degraded ? [`${degraded} degraded (stale or partial)`] : [])
  ];
  return `[docs/live-all-ops.md](docs/live-all-ops.md) (${generated}): ${pass} of ${total} pass, ${fail} fail; ${notes.join(", ")}.`;
}
